### ISSUE TITLE
BUG:   File "/BreakingBad/multi_part_assembly/models/vnn/network.py", line 209, in forward     global_inv_feats.reshape( RuntimeError: shape '[-1, 1024, 1024]' is invalid for input of size 276480

### ISSUE THREAD

**Issue by wzm2256** [crtie/Leveraging-SE-3-Equivariance-for-Learning-3D-Geometric-Shape-Assembly#1]
Hi, thanks for sharing your code. 

I'm running the script on breaking bad dataset and getting this error. Any idea how to resolve this?

By the way, the `set_trace` in line 56 in the same file should be comment out, otherwise the code will break in that line. Is this the final version of your code?

**Comment by wzm2256** [comment]
The error is caused by reshaping a tensor of shape `(batch_size, num_parts, 2*feat_dim, 3)` to `(batch_size, 2*feat_dim, 2*feat_dim)`.

**Comment by warshallrho** [comment]
> Hi, thanks for sharing your code.
> 
> I'm running the script on breaking bad dataset and getting this error. Any idea how to resolve this?
> 
> By the way, the `set_trace` in line 56 in the same file should be comment out, otherwise the code will break in that line. Is this the final version of your code?

For the `set_trace` issue, the released code will not run into those lines.

**Comment by crtie** [comment]
This was an oversight when we released the code, which has been corrected.
