### ISSUE TITLE
undefined variables

### ISSUE THREAD

**Issue by wzm2256** [crtie/Leveraging-SE-3-Equivariance-for-Learning-3D-Geometric-Shape-Assembly#2]
Hi again, variable `quat_A` in line 227 in [ file 'GSM/shape_assembly/datasets/baseline/dataloader_CR.py'](https://github.com/crtie/Leveraging-SE-3-Equivariance-for-Learning-3D-Geometric-Shape-Assembly/blob/main/GSM/shape_assembly/datasets/baseline/dataloader_CR.py) is not define. Any idea how to resolve this?

**Comment by warshallrho** [comment]
> Hi again, variable `quat_A` in line 227 in [ file 'GSM/shape_assembly/datasets/baseline/dataloader_CR.py'](https://github.com/crtie/Leveraging-SE-3-Equivariance-for-Learning-3D-Geometric-Shape-Assembly/blob/main/GSM/shape_assembly/datasets/baseline/dataloader_CR.py) is not define. Any idea how to resolve this?

Hi, we do not use quaternion for training, and thus the code will not run into lines related to quat_A/B. Thanks for pointing this out, and I have updated the code for purity.
