### ISSUE TITLE
one question about "dataverse_files/everyday.train.txt"

### ISSUE THREAD

**Issue by pluto2D** [crtie/Leveraging-SE-3-Equivariance-for-Learning-3D-Geometric-Shape-Assembly#5]
Dear author, 

When I run 'python scripts/train.py --cfg_file configs/vnn/vnn-everyday.py', it shows 'No such file or directory ../dataverse_files/everyday.train.txt', it seems like there is a txt file got lost, could you please tell me how to get it?

**Comment by crtie** [comment]
Thank you for your interest in our work!
The file you mentioned is a part of "BreakingBad" dataset. You can refer to https://github.com/Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io/blob/main/README.md for detailed usage of the dataset.
Best.

**Comment by crtie** [comment]
Maybe you just need to download the BreakingBad dataset, and then you will be able to run our code successfully.
