### ISSUE TITLE
One question about 'recon_pts in pred_dict'

### ISSUE THREAD

**Issue by pluto2D** [crtie/Leveraging-SE-3-Equivariance-for-Learning-3D-Geometric-Shape-Assembly#8]
Dear authors,

I had tried to run the train.py, and I find that the 'recon_pts' and 'whole_recon_pcs' are not included in 'pre_dict'. Is there any way to get these two values?

**Comment by crtie** [comment]
As we mentioned in our paper, the reconstruction module is an incremental module. The performance improment brought by this module is not critical. But adding this module will result in a larger memory cost and slower training speed. Therefore, we recommend not using reconstruction module in practical use.
